import { Deck } from './Deck.js';
import { Hand } from './Hand.js';
import { playDealer } from './DealerAI.js';
import type { Card } from './Card.js';
export type GamePhase='waiting'|'betting'|'player_turn'|'dealer_turn'|'result';
export interface Stats{handsPlayed:number;wins:number;losses:number;pushes:number;blackjacks:number;totalWagered:number;totalWon:number;totalLost:number;}
export interface PublicState{phase:GamePhase;balance:number;bet:number;player:{cards:Card[];score:number;status:string};dealer:{cards:Array<Card|null>;score:number|null;hidden:boolean;status:string};stats:Stats;result?:string;payout?:number;canDouble:boolean;}
export class BlackjackGame {
 balance=10000;bet=0;phase:GamePhase='betting';player=new Hand();dealer=new Hand();deck:Deck;stats:Stats={handsPlayed:0,wins:0,losses:0,pushes:0,blackjacks:0,totalWagered:0,totalWon:0,totalLost:0};result?:string;payout=0;
 constructor(opts:{deck?:Deck;balance?:number}={}){this.deck=opts.deck??new Deck();if(opts.balance!==undefined)this.balance=opts.balance;}
 placeBet(amount:number){if(this.phase!=='betting')throw new Error('Betting is closed');if(!Number.isInteger(amount)||amount<=0||amount>1000000)throw new Error('Invalid bet');if(amount>this.balance)throw new Error('Insufficient chips');this.bet=amount;this.balance-=amount;this.stats.totalWagered+=amount;this.startRound();}
 private startRound(){this.player=new Hand();this.dealer=new Hand();this.result=undefined;this.payout=0;this.phase='player_turn';this.player.add(this.deck.draw());this.dealer.add(this.deck.draw());this.player.add(this.deck.draw());this.dealer.add(this.deck.draw());if(this.player.isBlackjack()||this.dealer.isBlackjack())this.resolveBlackjack();}
 hit(){this.requirePlayerTurn();this.player.add(this.deck.draw());if(this.player.isBust()){this.player.status='bust';this.resolve();}else if(this.player.getScore()===21)this.stand();}
 stand(){this.requirePlayerTurn();this.player.status='stand';this.phase='dealer_turn';playDealer(this.dealer,this.deck);this.resolve();}
 doubleDown(){this.requirePlayerTurn();if(this.player.cards.length!==2)throw new Error('Double Down is only available on two cards');if(this.balance<this.bet)throw new Error('Insufficient chips');this.balance-=this.bet;this.stats.totalWagered+=this.bet;this.bet*=2;this.player.add(this.deck.draw());this.player.status=this.player.isBust()?'bust':'stand';this.phase='dealer_turn';playDealer(this.dealer,this.deck);this.resolve();}
 private requirePlayerTurn(){if(this.phase!=='player_turn')throw new Error('You cannot act right now');}
 private resolveBlackjack(){this.phase='result';this.stats.handsPlayed++;if(this.player.isBlackjack()&&this.dealer.isBlackjack()){this.result='PUSH';this.payout=this.bet;this.balance+=this.bet;this.stats.pushes++;this.player.status='push';this.dealer.status='push';}else if(this.player.isBlackjack()){this.result='BLACKJACK';this.payout=this.bet*2.5;this.balance+=this.payout;this.stats.wins++;this.stats.blackjacks++;this.stats.totalWon+=this.bet*1.5;this.player.status='blackjack';this.dealer.status='lose';}else{this.result='DEALER WINS';this.stats.losses++;this.stats.totalLost+=this.bet;this.player.status='lose';this.dealer.status='win';}}
 private resolve(){this.phase='result';this.stats.handsPlayed++;if(this.player.isBust()){this.result='DEALER WINS';this.stats.losses++;this.stats.totalLost+=this.bet;this.player.status='lose';this.dealer.status='win';return;}if(this.dealer.isBust()){this.result='YOU WIN';this.balance+=this.bet*2;this.stats.wins++;this.stats.totalWon+=this.bet;this.player.status='win';this.dealer.status='bust';return;}const p=this.player.getScore(),d=this.dealer.getScore();if(p>d){this.result='YOU WIN';this.balance+=this.bet*2;this.stats.wins++;this.stats.totalWon+=this.bet;this.player.status='win';this.dealer.status='lose';}else if(p<d){this.result='DEALER WINS';this.stats.losses++;this.stats.totalLost+=this.bet;this.player.status='lose';this.dealer.status='win';}else{this.result='PUSH';this.balance+=this.bet;this.stats.pushes++;this.player.status='push';this.dealer.status='push';}}
 newRound(){if(this.phase!=='result')throw new Error('Round is not finished');this.bet=0;this.phase='betting';this.player=new Hand();this.dealer=new Hand();}
 getState():PublicState{const hidden=this.phase==='player_turn';return {phase:this.phase,balance:this.balance,bet:this.bet,player:{cards:this.player.cards,score:this.player.getScore(),status:this.player.status},dealer:{cards:hidden?[this.dealer.cards[0],null]:this.dealer.cards,score:hidden?null:this.dealer.getScore(),hidden,status:this.dealer.status},stats:this.stats,result:this.result,payout:this.payout,canDouble:this.phase==='player_turn'&&this.player.cards.length===2&&this.balance>=this.bet};}
}
